### ISSUE TITLE
Suggested fixes that I noticed

### ISSUE THREAD

**Issue by LTLA** [BiocPy/BiocFrame#67]
- [x] we should tone down the behavior of `__getitem__` so that any single-argument operator will perform subsetting on the rows. This is more consistent with a tuple that is missing its first argument. Currently some of the single-argument operators will perform subsetting on the columns, which is pretty confusing. (Fixed by #77.)
- [x] `combine()` should be split into `combine_rows()` and `combine_columns()`, which should be easy enough to do. (Fixed by #75.)
- [x] `combine_rows()` should not add any row names at all if the row names are `None` for all input objects. (Fixed by #74.)
- [x] Consider switching to `sphinx-autodoc-typehints` to avoid the need to manually specify the docstring types. (Fixed by #80.)
- [x] I'm pretty sure `remove_column()` will suffer the same issue as described in #64.
